import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/*
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'start',
    {
      type: 'category',
      label: '乱七八糟（',
      items: [{type: 'autogenerated', dirName: 'common'}],
    },
    {
      type: 'category',
      label: '游戏类指令',
      items: [{type: 'autogenerated', dirName: 'games'}],
    },
  ],
};
*/

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
