import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'init',
    {
      type: 'category',
      label: '游戏类指令',
      items: [{type: 'autogenerated', dirName: 'games'}],
    },
  ],
};

/*
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
*/
export default sidebars;
